name: CI

on: # когда запускать экшины
  push:  # если ктото пушит в ветку main, master
    branches: [ main, master ]
  pull_request: # или будет пул реквест
    branches: [ main, master ]

  jobs:
    build-and-test:
      runs-on: alpine:3.20.8
      steps:
        - uses: actions/checkout@v5

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.25.1'
            cache-dependency-path: go.sum

        - name: Build
          run: go build -o ./bin/ -v ./...

        - name: Test
          run: go test -v ./...

    linter:
      name: lint
      runs-on: alpine:3.20.8
      steps:
        - uses: actions/checkout@v5
        - uses: actions/setup-go@v5
          with:
            go-version: '1.25.1'
            cache: false
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v6
          with:
            version: v6
            args: --timeout=30m --config=./.golangci.pipeline.yaml

# TODO сделать джобу для деплоя без контейнера, сразу из гитхаба

      deploy:
        name: Deploy
        runs-on: alpine:3.20.8
        steps:
          - uses: actions/checkout@v5
          - uses: actions/setup-go@v5
            with:
              go-version: '1.25.1'
              cache: false
          - name: Deploy
            run: go run ./cmd/main.go
