name: CI

on: # когда запускать экшины
  push:  # если ктото пушит в ветку main, master
    branches: [ main, master ]
  pull_request: # или будет пул реквест
    branches: [ main, master ]

env:
  REGISTRY_USER: hack3r11
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  IMAGE_NAME: go-tg-bot
  CONTAINER_NAME: go-tg-bot-container

  jobs:
    build-and-test:
      runs-on: alpine:3.20.8
      steps:
        - uses: actions/checkout@v5

        - name: Set up Go
          uses: actions/setup-go@v5
          with:
            go-version: '1.25.1'
            cache-dependency-path: go.sum

        - name: Build
          run: go build -o ./bin/ -v ./...

        - name: Test
          run: go test -v ./...

    linter:
      name: lint
      runs-on: alpine:3.20.8
      steps:
        - uses: actions/checkout@v5
        - uses: actions/setup-go@v5
          with:
            go-version: '1.25.1'
            cache: false
        - name: golangci-lint
          uses: golangci/golangci-lint-action@v6
          with:
            version: v6
            args: --timeout=30m --config=./.golangci.pipeline.yaml

# TODO сделать джобу для деплоя без контейнера, сразу из гитхаба

    image-build-n-push:
      runs-on: ubuntu-24.04.1

      steps:
        - name: Checkout master/main
          uses: actions/checkout@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v5

        - name: Login to Docker Registry
          run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}  $REGISTRY

        - name: Build and Push Docker Image
          run: | # многострочная команда
            TAG_NAME=$(echo $GITHUB_SHA | head -c7) 
            docker buildx create --use
            docker buildx build --no-cache --push --tag $REGISTRY/$IMAGE_NAME:$TAG_NAME -f Dockerfile . 

    deploy-image:
      runs-on: ubuntu-24.04.1
      needs: image-build-n-push

      steps:
        - name: Deploy to Docker Hub Image
          run: | # многострочная команда
            TAG_NAME=$(echo $GITHUB_SHA | head -c7) 
            docker run -d --name $CONTAINER_NAME $REGISTRY/$IMAGE_NAME:$TAG_NAME
      
